### ISSUE TITLE
Library status

### ISSUE THREAD

**Issue by techiezia** [gunderson/omega2-io#1]
What is the status of the library currently?

**Comment by gunderson** [comment]
I got it running well enough to do what I needed to do (read/write gpio), but quickly decided that the portability that Johnny-five provides isn't enough of a value proposition to make building out a translation layer really worth the effort. I decided, just to code directly for node, instead.

At this point, I added code that **should** handle GPIO, SPI and I2C by using the linux sockets and included native utils provided by onion. Most of this is in-place but untested.
